version: "3"

services:
  # Database
  postgres:
    image: postgres:latest
    container_name: finance_app_postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  # Redis
  redis:
    image: redis:latest
    container_name: finance_app_redis
    ports: 
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

networks:
  mysql-phpmyadmin:

volumes:
  postgres_data: